image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules

pages:
  script:
    - npm run build
    - mv out/* site
    - rm -rf out
  artifacts:
    paths:
      - site
  only:
    - main